// tsup.config.ts
import { defineConfig } from 'tsup'

export default defineConfig({
  // 核心配置
  entry: ['src/index.ts'], // 入口文件
  format: ['cjs', 'esm'], // 生成 CJS 和 ESM 格式
  outDir: 'dist', // 输出目录
  dts: true, // 生成类型声明文件
  clean: true, // 构建前清空输出目录

  // 关键扩展配置
  outExtension({ format }) {
    return {
      js: format === 'esm' ? '.mjs' : '.js', // ESM 用 .mjs 扩展名
    }
  },
  target: 'esnext', // 编译目标语法
  minify: true, // 关闭代码压缩
  sourcemap: false, // 生成 sourcemap
  treeshake: true, // 启用 Tree-Shaking

  // 高级配置
  splitting: false, // 关闭代码拆分（库项目通常不需要）
  skipNodeModulesBundle: true, // 不打包 node_modules
  external: ['vite'], // 外部化依赖（如 Vite）
  banner: {
    // 添加文件头注释
    js: '// Generated by tsup\n',
  },
})
